#!/bin/bash

set -euo pipefail

repo=
register=
verbose=

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            printf 'Usage: gh get [-r] [-v] <user>/<repo>\n'
            printf '       gh get [-r] [-v] https://github.com/<user>/<repo>\n'
            printf '       gh get [-r] [-v] https://github.com/<user>/<repo>.git\n'
            exit 0
            ;;
        -r|--register)
            register=1
            ;;
        -v|--verbose)
            verbose=1
            ;;
        *)
            repo="$1"
            ;;
    esac

    shift
done

if [[ $repo =~ ^https://github.com/ ]]; then
    repo="${repo#https://github.com/}"
    repo="${repo%.git}"
fi

dest="$HOME/src/github.com/${repo}"
mrconfig="$( dirname "$dest" )/.mrconfig"

if [[ -e "$dest" ]]; then
    if [[ -n "$verbose" ]]; then
        printf '%s: %s: destination exists\n' "$0" "$dest"
    fi
    exit 0
fi

gh repo clone "$repo" "$dest"

if [[ -n "$register" ]]; then
    if [[ ! -e "$mrconfig" ]]; then
        touch "$mrconfig"
    fi
    mr -c "$mrconfig" register "$dest"
fi
